// Visible per-platform answer box for SEO (1 page = 1 query).
// Rendered OPEN in SSR HTML (not collapsed) so crawlers weight it.
// Returns null for admob/home/trust/404 so those pages stay byte-identical.
import React from "react";
import { useTranslation } from "../i18n/LanguageContext";

interface SpotlightEntry {
  h2: string;
  p1: string;
  p2: string;
  bullets: [string, string, string];
  q1: string;
  a1: string;
  q2: string;
  a2: string;
}

const SPOTLIGHT: Record<string, Record<string, SpotlightEntry>> = {
  en: {
    adsense: {
      h2: "How much does AdSense pay per 1,000 views?",
      p1: "In 2026 AdSense pays roughly $2.50 to $45+ per 1,000 pageviews. Finance, insurance, SaaS and legal sites with Tier 1 traffic (US, UK, CA, AU) earn $25–$60 Page RPM, while entertainment, humor and gaming average $2–$7. Formula: Revenue = (Pageviews × Page RPM) / 1,000. Google shares 68% of ad revenue with publishers.",
      p2: "Three things move the number most: audience geography (Tier 1 pays 4–10x Tier 3), Active View viewability above 70% (up to 3x higher bids) and ad-block loss (15–45% on tech/gaming). Q4 holiday budgets lift CPMs 30–55% over January.",
      bullets: ["$1,000/mo ≈ 40,000 views at $25 RPM · ≈166,000 at $6 RPM", "Revenue share: 68% content / 51% search", "Targets: viewability >70% · 2–4 units per page"],
      q1: "What is the difference between Page RPM and CPC?",
      a1: "Page RPM is earnings per 1,000 pageviews across all ad units. CPC is what one advertiser pays per click. Use the calculator above with your niche and viewability to get your Page RPM.",
      q2: "How many pageviews do I need to make $1,000 a month?",
      a2: "Divide 1,000 by your RPM and multiply by 1,000: at $25 RPM you need ~40,000 views, at $6 RPM ~166,000 views.",
    },
    youtube: {
      h2: "How much does YouTube pay per 1,000 views?",
      p1: "In 2026 long-form RPM ranges from $1.50 to $35+ per 1,000 views. Finance, crypto, SaaS and real estate earn $15–$35 in Tier 1 countries, while gaming and entertainment average $2–$6. YouTube keeps 45% and pays creators 55%. Shorts are pooled separately at roughly $0.03–$0.09 RPM.",
      p2: "Videos over 8 minutes unlock mid-roll breaks worth +35–60% RPM. Channel memberships ($4.99/mo, 70% net) and Super Chats stack on top. Partner Program entry: 1,000 subs + 4,000 watch hours, or 500 subs + 3M Shorts views in 90 days.",
      bullets: ["RPM = CPM × 55% × monetized-view share", "Finance 1M views ≈ $15,000–$35,000 · gaming ≈ $2,000–$6,000", "Shorts 1M views ≈ $30–$90"],
      q1: "Why is RPM lower than CPM?",
      a1: "CPM is what advertisers pay per 1,000 ad impressions. RPM is what you keep per 1,000 video views after YouTube's 45% cut and non-monetized views.",
      q2: "How many views do I need to make $1,000 a month?",
      a2: "At a $5 RPM you need ~200,000 monthly views; at $20 RPM (finance, US audience) ~50,000 views.",
    },
    tiktok: {
      h2: "How much does TikTok pay per 1,000 views?",
      p1: "The Creator Rewards Program pays roughly $0.40–$1.20 per 1,000 qualified views. Only original videos over 1 minute count, and only views watched 5+ seconds from the For You feed qualify — typically ~45% of total views. So 1M total views ≈ $200–$800 effective.",
      p2: "LIVE gifts convert to Diamonds at $0.005 each with a 50% net payout: 100,000 Diamonds = $250. Enter your monthly views, qualified-view rate and diamonds above for an exact estimate.",
      bullets: ["Qualified = >1 min · >5s watch · For You feed", "1 Diamond = $0.005 (50% net) · 200 Diamonds = $1", "Shop affiliates add 10–20% GMV commission"],
      q1: "How much is 1,000 TikTok Diamonds worth?",
      a1: "1,000 Diamonds = $5 net to the creator. Viewers pay roughly double that in coins before TikTok's cut.",
      q2: "Do all TikTok views count for payment?",
      a2: "No. Replays under 5 seconds, non-For-You traffic and videos under 1 minute are excluded from Rewards payouts.",
    },
    twitch: {
      h2: "How much does 1 Twitch sub pay?",
      p1: "A $4.99 Tier 1 sub pays $2.49 at the standard 50/50 split and ~$3.49 at the 70/30 Partner Plus split. Tier 2 ($9.99) and Tier 3 ($24.99) scale proportionally. So 100 Tier 1 subs ≈ $249/mo at 50/50 versus ≈$349/mo at 70/30.",
      p2: "Partner Plus unlocks 60/40 at 100 Plus Points and 70/30 at 350 Plus Points held 3 months (Tier 1 = 1 pt, Tier 2 = 2 pts, Tier 3 = 6 pts). The Ad Incentive Program (AIP) adds ~$3.50–$10 per viewer-hour for 2–3 ad minutes per hour, plus $0.01 per Bit.",
      bullets: ["100 Tier 1 subs: $249 (50/50) · $349 (70/30)", "Plus Points: 100 → 60/40 · 350 → 70/30", "Bits: 100 bits = $1 · 1,000 bits = $10"],
      q1: "How do I unlock the Twitch 70/30 split?",
      a1: "Hold 350 Plus Points for 3 consecutive months from recurring paid subs (Prime and one-off gifts excluded).",
      q2: "What does the Twitch Ad Incentive Program pay?",
      a2: "A fixed hourly rate for running 2–3 minutes of ads per hour — model it above with your CCV and monthly hours.",
    },
    kick: {
      h2: "How much does Kick pay per sub?",
      p1: "Kick keeps 5% and pays creators 95%: $4.74 net per $4.99 subscription — nearly double Twitch's $2.49 baseline. 100 subs ≈ $474/mo and 1,000 subs ≈ $4,740/mo from subs alone, before tips and hourly pay.",
      p2: "The Kick Creator Incentive Program (KCIP/KCP) adds roughly $16–$40+/hr based on average concurrent viewers (CCV), hours streamed and chat engagement. Direct tips are 100% net.",
      bullets: ["$4.74 net per $4.99 sub (95/5) vs $2.49 Twitch 50/50", "KCP hourly ≈ $16–$40+/hr by CCV", "100 subs ≈ $474/mo · 1,000 subs ≈ $4,740/mo"],
      q1: "Does Kick really pay $16 an hour?",
      a1: "Eligible partners earn an hourly stipend scaled by CCV and hours streamed — enable KCP above to include it in your estimate.",
      q2: "Is Kick better paid than Twitch?",
      a2: "Per sub, yes: 95/5 versus 50/50–70/30. Compare both with the same CCV and hours in the calculators above.",
    },
    runway: {
      h2: "How long will my savings last?",
      p1: "Divide your balance by your monthly shortfall: $60,000 ÷ $5,000/mo = 12 months. With returns, money lasts longer — at 8% annual return a balance supports about 0.67% monthly withdrawal almost indefinitely. Enter your principal, withdrawal, return and inflation above for the year-by-year projection.",
      p2: "This is Systematic Withdrawal Plan (SWP) math: a fixed amount leaves monthly while the rest stays invested. The 4% rule is the same idea at 4%/year — adjust it for local inflation and taxes.",
      bullets: ["Runway ≈ balance ÷ (expenses − income)", "8% return supports ≈0.67%/mo long-term", "Raise inflation 1% → years drop fast: test it above"],
      q1: "How much can I withdraw per month safely?",
      a1: "Try 0.5–0.67% of balance per month at 6–8% returns, then check the breakeven line in the projection above.",
      q2: "Is this an SWP calculator?",
      a2: "Yes — a fixed monthly withdrawal with the remainder compounding, minus inflation step-up.",
    },
    "fuel-cost-calculator": {
      h2: "How do you calculate fuel cost for a trip?",
      p1: "Fuel needed = Distance ÷ Mileage, then Cost = Fuel × Pump price. Example: 300 km at 15 km/L needs 20 litres; at $1.20/L the trip costs $24. Cost per km = total ÷ distance.",
      p2: "The calculator above converts km/L, L/100km and mpg automatically, and handles round-trips, monthly repeats and per-passenger splits for any country.",
      bullets: ["Fuel = distance ÷ efficiency · Cost = fuel × price", "Per-km = total cost ÷ distance", "Round-trip ×2 · per person ÷ passengers"],
      q1: "How much fuel will my car use for 100 km?",
      a1: "100 ÷ your km/L: at 15 km/L you need ~6.7 litres. At 7 L/100km you need exactly 7 litres.",
      q2: "What is the cost per mile formula?",
      a2: "(Price per gallon ÷ MPG) = cost per mile. Multiply by trip miles for the total.",
    },
    "8th-pay-commission": {
      h2: "What is the 8th Pay Commission fitment factor?",
      p1: "The multiplier converting 7th CPC basic pay to 8th CPC basic: New Basic = Current Basic × Fitment Factor. Analyst consensus is ~1.92x (7th CPC used 2.57x); staff unions demand up to 3.83x. DA resets to 0% with HRA at 30/20/10% slabs. Try every scenario in the calculator above.",
      p2: "Revised pay applies from 1 January 2026 with arrears paid after the report (expected mid-2027) and Cabinet approval. Projections here, not official figures.",
      bullets: ["1.92x → ₹18,000 becomes ₹34,560", "DA resets to 0% · HRA X30 / Y20 / Z10", "Arrears counted from 1 Jan 2026"],
      q1: "How is new basic pay calculated?",
      a1: "Current 7th CPC basic × fitment factor, then add reset DA and slab HRA on the new basic.",
      q2: "When will the 8th Pay Commission be implemented?",
      a2: "Effective 1 Jan 2026 for pay fixation with arrears; cash payout follows the report and approval.",
    },
  },
  es: {
    adsense: {
      h2: "¿Cuánto paga AdSense por cada 1.000 visitas?",
      p1: "En 2026 AdSense paga entre $2,50 y más de $45 por cada 1.000 páginas vistas. Finanzas, seguros, SaaS y legal con tráfico Tier 1 (EE.UU., Reino Unido, Canadá) logran $25–$60 de RPM de página; entretenimiento y gaming promedian $2–$7. Fórmula: Ingresos = (Visitas × RPM) / 1.000. Google reparte el 68% con el editor.",
      p2: "Lo que más mueve el RPM: geografía (Tier 1 paga 4–10x más que Tier 3), visibilidad activa superior al 70% (hasta 3x más puja) y pérdida por AdBlock (15–45%). El Q4 navideño sube los CPM un 30–55%.",
      bullets: ["$1.000/mes ≈ 40.000 visitas con RPM $25 · ≈166.000 con RPM $6", "Reparto: 68% contenido / 51% búsqueda", "Objetivos: visibilidad >70% · 2–4 bloques por página"],
      q1: "¿Qué diferencia hay entre RPM de página y CPC?",
      a1: "El RPM mide ingresos por 1.000 páginas vistas con todos los bloques. El CPC es lo que paga un anunciante por clic.",
      q2: "¿Cuántas visitas necesito para ganar $1.000 al mes?",
      a2: "Unas 40.000 con RPM $25 (finanzas) o unas 166.000 con RPM $6 (temática general).",
    },
    youtube: {
      h2: "¿Cuánto paga YouTube por cada 1.000 visitas?",
      p1: "En 2026 el RPM de videos largos va de $1,50 a más de $35 por 1.000 vistas. Finanzas, cripto y SaaS logran $15–$35 en Tier 1; gaming y entretenimiento promedian $2–$6. YouTube retiene el 45% y paga el 55% al creador. Los Shorts se reparten aparte, unos $0,03–$0,09 de RPM.",
      p2: "Los videos de más de 8 minutos activan mid-rolls (+35–60% de RPM). Las membresías ($4,99/mes, 70% neto) y Super Chats suman. Para monetizar: 1.000 subs + 4.000 horas, o 500 subs + 3M de vistas de Shorts en 90 días.",
      bullets: ["RPM = CPM × 55% × vistas monetizadas", "1M de vistas finanzas ≈ $15.000–$35.000 · gaming ≈ $2.000–$6.000", "1M de Shorts ≈ $30–$90"],
      q1: "¿Por qué el RPM es menor que el CPM?",
      a1: "El CPM es lo que paga el anunciante; el RPM es lo que recibes tras la comisión del 45% y las vistas sin anuncio.",
      q2: "¿Cuántas vistas necesito para ganar $1.000 al mes?",
      a2: "Unas 200.000 con RPM $5, o unas 50.000 con RPM $20 (finanzas, audiencia EE.UU.).",
    },
    tiktok: {
      h2: "¿Cuánto paga TikTok por cada 1.000 visitas?",
      p1: "El Creator Rewards Program paga unos $0,40–$1,20 por cada 1.000 vistas calificadas. Solo cuentan videos originales de más de 1 minuto vistos 5+ segundos desde «Para ti» (típicamente ~45% del total). 1M de vistas totales ≈ $200–$800 efectivos.",
      p2: "Los regalos LIVE se convierten en diamantes a $0,005 cada uno con 50% neto: 100.000 diamantes = $250. Introduce tus vistas, tasa calificada y diamantes arriba.",
      bullets: ["Calificada = >1 min · >5s · feed «Para ti»", "1 diamante = $0,005 (50% neto) · 200 = $1", "TikTok Shop añade 10–20% de comisión"],
      q1: "¿Cuánto valen 1.000 diamantes de TikTok?",
      a1: "1.000 diamantes = $5 netos para el creador. El espectador pagó aproximadamente el doble en monedas.",
      q2: "¿Todas las vistas de TikTok cuentan para el pago?",
      a2: "No. Las vistas de menos de 5 segundos, fuera de «Para ti» y videos de menos de 1 minuto quedan excluidas.",
    },
    twitch: {
      h2: "¿Cuánto paga Twitch por sub?",
      p1: "Una sub Nivel 1 ($4,99) paga $2,49 con el reparto 50/50 y ~$3,49 con el 70/30 de Partner Plus. 100 subs Nivel 1 ≈ $249/mes al 50/50 frente a ≈$349/mes al 70/30.",
      p2: "Partner Plus da 60/40 con 100 Plus Points y 70/30 con 350 puntos durante 3 meses (Nivel 1 = 1 pt, Nivel 2 = 2, Nivel 3 = 6). El programa AIP añade ~$3,50–$10 por hora de espectador con 2–3 minutos de anuncios por hora, más $0,01 por Bit.",
      bullets: ["100 subs Nivel 1: $249 (50/50) · $349 (70/30)", "Plus Points: 100 → 60/40 · 350 → 70/30", "Bits: 100 bits = $1 · 1.000 bits = $10"],
      q1: "¿Cómo consigo el 70/30 en Twitch?",
      a1: "Mantén 350 Plus Points 3 meses consecutivos con subs de pago recurrentes (sin Prime ni regaladas únicas).",
      q2: "¿Cuánto paga el programa AIP de anuncios?",
      a2: "Una tarifa fija por hora por emitir 2–3 minutos de anuncios por hora; calcúlala arriba con tu CCV.",
    },
    kick: {
      h2: "¿Cuánto paga Kick por sub?",
      p1: "Kick se queda el 5% y paga el 95%: $4,74 netos por cada suscripción de $4,99, casi el doble que los $2,49 de Twitch. 100 subs ≈ $474/mes y 1.000 subs ≈ $4.740/mes solo en subs.",
      p2: "El programa KCP añade unos $16–$40+/hora según espectadores concurrentes (CCV), horas y chat. Las propinas directas son 100% netas.",
      bullets: ["$4,74 netos por sub (95/5) frente a $2,49 en Twitch", "KCP ≈ $16–$40+/hora según CCV", "100 subs ≈ $474/mes · 1.000 ≈ $4.740/mes"],
      q1: "¿Kick paga de verdad $16 por hora?",
      a1: "Los partners elegibles reciben un estipendio horario según CCV y horas; actívalo arriba (KCP).",
      q2: "¿Paga más Kick que Twitch?",
      a2: "Por sub, sí: 95/5 frente a 50/50–70/30. Compáralos con el mismo CCV arriba.",
    },
    runway: {
      h2: "¿Cuánto durarán mis ahorros?",
      p1: "Divide tu saldo entre tu déficit mensual: $60.000 ÷ $5.000/mes = 12 meses. Con rentabilidad dura más: al 8% anual, un saldo soporta ~0,67% de retiro mensual casi indefinidamente. Introduce tus cifras arriba para la proyección año a año.",
      p2: "Es matemática de retiro sistemático (SWP): una cantidad fija sale cada mes mientras el resto sigue invertido. La regla del 4% es la misma idea al 4%/año.",
      bullets: ["Runway ≈ saldo ÷ (gastos − ingresos)", "8% sostiene ≈0,67%/mes a largo plazo", "Sube la inflación 1% y los años caen: pruébalo arriba"],
      q1: "¿Cuánto puedo retirar al mes sin descapitalizarme?",
      a1: "Prueba 0,5–0,67% del saldo al mes con 6–8% de rentabilidad y revisa el punto de equilibrio.",
      q2: "¿Es esto una calculadora SWP?",
      a2: "Sí: retiro mensual fijo con el resto capitalizándose, menos el aumento por inflación.",
    },
    "fuel-cost-calculator": {
      h2: "¿Cómo se calcula el costo de combustible de un viaje?",
      p1: "Combustible = Distancia ÷ Consumo; Costo = Combustible × Precio. Ejemplo: 300 km a 15 km/L necesitan 20 litros; a $1,20/L el viaje cuesta $24. Costo por km = total ÷ distancia.",
      p2: "La calculadora convierte km/L, L/100km y mpg, e incluye ida y vuelta, repeticiones mensuales y reparto por pasajero en cualquier país.",
      bullets: ["Combustible = distancia ÷ consumo · Costo = litros × precio", "Por km = costo total ÷ distancia", "Ida y vuelta ×2 · por persona ÷ pasajeros"],
      q1: "¿Cuánto combustible gasto en 100 km?",
      a1: "100 ÷ tu km/L: con 15 km/L necesitas ~6,7 litros. Con 7 L/100km necesitas exactamente 7 litros.",
      q2: "¿Cómo calculo el costo por milla?",
      a2: "(Precio por galón ÷ MPG) = costo por milla. Multiplica por las millas del viaje.",
    },
    "8th-pay-commission": {
      h2: "What is the 8th Pay Commission fitment factor?",
      p1: "The multiplier converting 7th CPC basic pay to 8th CPC basic: New Basic = Current Basic × Fitment Factor. Consensus ~1.92x (7th CPC used 2.57x); unions demand up to 3.83x. DA resets to 0% with HRA at 30/20/10%.",
      p2: "Effective 1 January 2026 with arrears after the report (expected mid-2027). Projections, not official figures.",
      bullets: ["1.92x → ₹18,000 becomes ₹34,560", "DA 0% · HRA X30 / Y20 / Z10", "Arrears from 1 Jan 2026"],
      q1: "How is new basic pay calculated?",
      a1: "Current 7th CPC basic × fitment factor, then reset DA and slab HRA on the new basic.",
      q2: "When will it be implemented?",
      a2: "Fixation from 1 Jan 2026; cash payout after the report and approval.",
    },
  },
  ja: {
    adsense: {
      h2: "AdSenseは1,000回表示でいくら稼げる？",
      p1: "2026年のAdSenseは1,000PVあたり約$2.50〜$45以上。金融・保険・SaaS・法律系でTier1トラフィック（米・英・加・豪）の場合$25〜$60のページRPM、エンタメ・ゲーム系は$2〜$7が目安です。計算式：収益＝（PV×ページRPM）÷1,000。レベニューシェアは68%です。",
      p2: "収益を左右するのは地域（Tier1はTier3の4〜10倍）、視認率70%超（最大3倍の入札）、AdBlock損失（15〜45%）。Q4の繁忙期は1月比でCPMが30〜55%上昇します。",
      bullets: ["月$1,000＝RPM$25なら約4万PV・RPM$6なら約16.6万PV", "レベニューシェア：コンテンツ68%／検索51%", "目標：視認率70%超・広告枠2〜4つ"],
      q1: "ページRPMとCPCの違いは？",
      a1: "ページRPMは全広告枠込みの1,000PVあたり収益、CPCは1クリックあたりの広告主支払額です。",
      q2: "月$1,000稼ぐのに必要なPV数は？",
      a2: "RPM$25なら約4万PV、RPM$6なら約16.6万PVが目安です。",
    },
    youtube: {
      h2: "YouTubeは1,000回再生でいくら稼げる？",
      p1: "2026年の長尺動画RPMは1,000回再生あたり$1.50〜$35以上。金融・暗号資産・SaaSはTier1で$15〜$35、ゲーム・エンタメは$2〜$6が目安。YouTubeが45%を取り、クリエイター取り分は55%。ショートは別プールで約$0.03〜$0.09のRPMです。",
      p2: "8分超の動画はミッドロール広告でRPMが約35〜60%向上。メンバーシップ（$4.99/月・取り分70%）とスーパーチャットが上乗せ。収益化条件は登録者1,000人＋4,000時間、または500人＋90日でショート300万回視聴です。",
      bullets: ["RPM＝CPM×55%×収益化視聴率", "100万回：金融$15,000〜$35,000・ゲーム$2,000〜$6,000", "ショート100万回≈$30〜$90"],
      q1: "RPMがCPMより低いのはなぜ？",
      a1: "CPMは広告主の支払額、RPMは45%控除後・非収益化視聴込みの受取額だからです。",
      q2: "月$1,000稼ぐのに必要な再生数は？",
      a2: "RPM$5なら月約20万回、RPM$20（金融・米国向け）なら約5万回が目安です。",
    },
    tiktok: {
      h2: "TikTokは1,000回視聴でいくら稼げる？",
      p1: "Creator Rewardsは対象1,000回視聴あたり約$0.40〜$1.20。1分超のオリジナル動画をおすすめフィードで5秒以上視聴されたもののみ対象で、全体の約45%が該当します。100万回再生の実効収益は約$200〜$800です。",
      p2: "LIVEギフトはダイヤモンド換算で1個$0.005、取り分50%：10万ダイヤ＝$250。上で月間再生数・対象率・ダイヤ数を入力してください。",
      bullets: ["対象＝1分超・5秒以上・おすすめ経由", "1ダイヤ＝$0.005（50%）・200個＝$1", "Shopアフィリエイトで＋10〜20%"],
      q1: "1,000ダイヤモンドはいくら？",
      a1: "クリエイター受取で$5。視聴者のコイン課金額は約2倍です。",
      q2: "すべての再生が報酬対象になる？",
      a2: "いいえ。5秒未満・おすすめ外・1分未満の動画は対象外です。",
    },
    twitch: {
      h2: "Twitchのサブスク1件あたりの収益は？",
      p1: "$4.99のTier1サブは通常配分50/50で$2.49、Partner Plusの70/30で約$3.49。100件なら月$249（50/50）対$349（70/30）です。",
      p2: "Partner Plusは100ポイントで60/40、350ポイント3ヶ月維持で70/30（Tier1＝1pt・Tier2＝2pt・Tier3＝6pt）。AIP広告は1時間2〜3分の配信で視聴者1人時あたり約$3.50〜$10、Bitsは1bit＝$0.01です。",
      bullets: ["Tier1×100件：$249（50/50）・$349（70/30）", "100pt→60/40・350pt→70/30", "100bits＝$1・1,000bits＝$10"],
      q1: "70/30配分になる条件は？",
      a1: "有料継続サブで350ポイントを3ヶ月連続維持（Prime・単発ギフトは対象外）です。",
      q2: "AIP広告収入はいくら？",
      a2: "1時間あたり固定額。上でCCVと配信時間を入力して試算してください。",
    },
    kick: {
      h2: "Kickのサブスク1件あたりの収益は？",
      p1: "Kickは手数料5%・還元95%：$4.99のサブで$4.74が取り分で、Twitchの$2.49の約2倍。100件で月約$474、1,000件で約$4,740（サブのみ）です。",
      p2: "KCP（Creator Program）は平均同時視聴者（CCV）・配信時間・チャット活発度で約$16〜$40+/時。投げ銭は100%還元です。",
      bullets: ["$4.74/件（95/5）対Twitch $2.49", "KCP時給≈$16〜$40+/時", "100件≈$474/月・1,000件≈$4,740/月"],
      q1: "本当に時給$16もらえる？",
      a1: "条件達成パートナーにCCV連動の時給が支給されます。上でKCPを有効化してください。",
      q2: "KickとTwitchはどちらが稼げる？",
      a2: "サブ単価はKickが約2倍。同じCCV・時間で上で比較できます。",
    },
    runway: {
      h2: "貯蓄は何年もつ？",
      p1: "残高÷毎月の不足額が目安：$60,000÷$5,000/月＝12ヶ月。運用利回りがあれば延命し、年利8%なら月0.67%の取り崩しをほぼ維持できます。上で元本・取崩額・利回り・インフレを入力してください。",
      p2: "毎月定額を取り崩し残りを運用するSWP計算です。4%ルール（年4%取崩し）と同じ考え方です。",
      bullets: ["寿命≈残高÷（支出−収入）", "年利8%で月0.67%が目安", "インフレ＋1%で寿命は大幅短縮"],
      q1: "毎月いくらまで取り崩せる？",
      a1: "利回り6〜8%なら月0.5〜0.67%を試し、損益分岐点を確認してください。",
      q2: "SWP計算機ですか？",
      a2: "はい。定額取崩し＋残高運用−インフレ上乗せの計算です。",
    },
    "fuel-cost-calculator": {
      h2: "旅行の燃料費の計算方法は？",
      p1: "必要燃料＝距離÷燃費、費用＝燃料×単価。例：300kmを15km/Lで走行なら20L、単価$1.20/Lで$24。1kmあたり＝合計÷距離です。",
      p2: "上ではkm/L・L/100km・mpgを自動換算し、往復・月間回数・割り勘に世界対応しています。",
      bullets: ["燃料＝距離÷燃費・費用＝燃料×単価", "1km単価＝合計÷距離", "往復×2・割勘÷人数"],
      q1: "100km走行の燃料は？",
      a1: "100÷km/L：15km/Lなら約6.7L。7L/100kmなら正確に7Lです。",
      q2: "1マイルあたりの費用は？",
      a2: "（1ガロン単価÷MPG）＝1マイル単価。距離を掛けて合計を算出します。",
    },
    "8th-pay-commission": {
      h2: "What is the 8th Pay Commission fitment factor?",
      p1: "The multiplier converting 7th CPC basic pay to 8th CPC basic: New Basic = Current Basic × Fitment Factor. Consensus ~1.92x (7th CPC used 2.57x); unions demand up to 3.83x. DA resets to 0% with HRA at 30/20/10%.",
      p2: "Effective 1 January 2026 with arrears after the report (expected mid-2027). Projections, not official figures.",
      bullets: ["1.92x → ₹18,000 becomes ₹34,560", "DA 0% · HRA X30 / Y20 / Z10", "Arrears from 1 Jan 2026"],
      q1: "How is new basic pay calculated?",
      a1: "Current 7th CPC basic × fitment factor, then reset DA and slab HRA on the new basic.",
      q2: "When will it be implemented?",
      a2: "Fixation from 1 Jan 2026; cash payout after the report and approval.",
    },
  },
  fr: {
    adsense: {
      h2: "Combien rapporte AdSense pour 1 000 vues ?",
      p1: "En 2026 AdSense paie environ 2,50 $ à plus de 45 $ pour 1 000 pages vues. Finance, assurance, SaaS et juridique en Tier 1 (US, UK, CA, AU) atteignent 25–60 $ de RPM page ; divertissement et gaming moyennent 2–7 $. Formule : Revenus = (Vues × RPM) / 1 000. Google reverse 68 % aux éditeurs.",
      p2: "Géographie (Tier 1 = 4–10x le Tier 3), visibilité active >70 % (jusqu'à 3x d'enchères) et bloqueurs (15–45 %) font l'écart. Le Q4 des fêtes gagne 30–55 % sur janvier.",
      bullets: ["1 000 $/mois ≈ 40 000 vues à 25 $ RPM · ≈166 000 à 6 $", "Partage : 68 % contenu / 51 % recherche", "Cibles : visibilité >70 % · 2–4 blocs par page"],
      q1: "Quelle différence entre RPM page et CPC ?",
      a1: "Le RPM mesure le gain pour 1 000 pages vues tous blocs confondus. Le CPC est le prix d'un clic payé par un annonceur.",
      q2: "Combien de vues pour gagner 1 000 $ par mois ?",
      a2: "Environ 40 000 à 25 $ RPM (finance) ou 166 000 à 6 $ RPM (généraliste).",
    },
    youtube: {
      h2: "Combien paie YouTube pour 1 000 vues ?",
      p1: "En 2026 le RPM long format va de 1,50 $ à plus de 35 $ pour 1 000 vues. Finance, crypto et SaaS atteignent 15–35 $ en Tier 1 ; gaming et divertissement moyennent 2–6 $. YouTube garde 45 % et reverse 55 %. Les Shorts sont mutualisés à part, environ 0,03–0,09 $ RPM.",
      p2: "Les vidéos de plus de 8 minutes débloquent les mid-rolls (+35–60 % RPM). Abonnements (4,99 $, 70 % net) et Super Chats s'ajoutent. Accès YPP : 1 000 abonnés + 4 000 heures, ou 500 abonnés + 3M vues Shorts sur 90 jours.",
      bullets: ["RPM = CPM × 55 % × vues monétisées", "1M vues finance ≈ 15 000–35 000 $ · gaming ≈ 2 000–6 000 $", "1M Shorts ≈ 30–90 $"],
      q1: "Pourquoi le RPM est-il inférieur au CPM ?",
      a1: "Le CPM est le coût annonceur ; le RPM est votre net après la part de 45 % et les vues non monétisées.",
      q2: "Combien de vues pour 1 000 $ par mois ?",
      a2: "Environ 200 000 à 5 $ RPM, ou 50 000 à 20 $ RPM (finance, audience US).",
    },
    tiktok: {
      h2: "Combien paie TikTok pour 1 000 vues ?",
      p1: "Le Creator Rewards paie environ 0,40–1,20 $ pour 1 000 vues qualifiées. Seules les vidéos originales de plus d'1 minute vues 5 s+ depuis « Pour toi » comptent (~45 % du total). 1M de vues totales ≈ 200–800 $ effectifs.",
      p2: "Les cadeaux LIVE deviennent des diamants à 0,005 $ (50 % net) : 100 000 diamants = 250 $. Saisissez vues, taux qualifié et diamants ci-dessus.",
      bullets: ["Qualifiée = >1 min · >5 s · fil « Pour toi »", "1 diamant = 0,005 $ (50 % net) · 200 = 1 $", "TikTok Shop ajoute 10–20 % de commission"],
      q1: "Combien valent 1 000 diamants TikTok ?",
      a1: "1 000 diamants = 5 $ nets créateur. Le spectateur a payé environ le double en pièces.",
      q2: "Toutes les vues TikTok comptent-elles ?",
      a2: "Non. Moins de 5 secondes, hors « Pour toi » et vidéos de moins d'1 minute sont exclues.",
    },
    twitch: {
      h2: "Combien rapporte 1 abonnement Twitch ?",
      p1: "Un sub Tier 1 (4,99 $) rapporte 2,49 $ en 50/50 et ~3,49 $ en 70/30 Partner Plus. 100 subs Tier 1 ≈ 249 $/mois en 50/50 contre ≈349 $/mois en 70/30.",
      p2: "Partner Plus offre 60/40 à 100 Plus Points et 70/30 à 350 points sur 3 mois (Tier 1 = 1 pt, Tier 2 = 2, Tier 3 = 6). Le programme AIP ajoute ~3,50–10 $ par heure-spectateur pour 2–3 minutes de pubs par heure, plus 0,01 $ par Bit.",
      bullets: ["100 subs Tier 1 : 249 $ (50/50) · 349 $ (70/30)", "Plus Points : 100 → 60/40 · 350 → 70/30", "Bits : 100 bits = 1 $ · 1 000 bits = 10 $"],
      q1: "Comment débloquer le 70/30 sur Twitch ?",
      a1: "Conservez 350 Plus Points 3 mois de suite via des subs payants récurrents (hors Prime et cadeaux uniques).",
      q2: "Combien paie le programme AIP ?",
      a2: "Un tarif horaire fixe pour 2–3 minutes de pubs par heure ; calculez-le ci-dessus avec votre CCV.",
    },
    kick: {
      h2: "Combien paie Kick par abonnement ?",
      p1: "Kick prélève 5 % et reverse 95 % : 4,74 $ nets par abonnement à 4,99 $, soit près du double des 2,49 $ de Twitch. 100 subs ≈ 474 $/mois et 1 000 subs ≈ 4 740 $/mois en subs seuls.",
      p2: "Le programme KCP ajoute environ 16–40 $+/heure selon les spectateurs simultanés (CCV), les heures et le chat. Les pourboires directs sont à 100 % nets.",
      bullets: ["4,74 $ nets par sub (95/5) contre 2,49 $ Twitch", "KCP ≈ 16–40 $+/heure selon CCV", "100 subs ≈ 474 $/mois · 1 000 ≈ 4 740 $/mois"],
      q1: "Kick paie-t-il vraiment 16 $ de l'heure ?",
      a1: "Les partenaires éligibles touchent un fixe horaire selon CCV et heures ; activez KCP ci-dessus.",
      q2: "Kick paie-t-il mieux que Twitch ?",
      a2: "Par sub, oui : 95/5 contre 50/50–70/30. Comparez à CCV égal ci-dessus.",
    },
    runway: {
      h2: "Combien de temps dureront mes économies ?",
      p1: "Divisez le solde par le manque mensuel : 60 000 $ ÷ 5 000 $/mois = 12 mois. Avec rendement c'est plus long — à 8 % annuel, un solde supporte ~0,67 % de retrait mensuel presque indéfiniment. Saisissez vos chiffres ci-dessus pour la projection année par année.",
      p2: "C'est le calcul du retrait systématique (SWP) : un montant fixe sort chaque mois pendant que le reste fructifie. La règle des 4 % en est la version à 4 %/an.",
      bullets: ["Horizon ≈ solde ÷ (dépenses − revenus)", "8 % supporte ≈0,67 %/mois long terme", "+1 % d'inflation = années en moins : testez ci-dessus"],
      q1: "Combien puis-je retirer par mois ?",
      a1: "Essayez 0,5–0,67 % du solde par mois à 6–8 % de rendement et vérifiez le seuil.",
      q2: "Est-ce un calculateur SWP ?",
      a2: "Oui : retrait mensuel fixe avec solde capitalisé, moins la hausse d'inflation.",
    },
    "fuel-cost-calculator": {
      h2: "Comment calculer le coût carburant d'un trajet ?",
      p1: "Carburant = Distance ÷ Consommation ; Coût = Carburant × Prix. Exemple : 300 km à 15 km/L = 20 litres ; à 1,20 $/L le trajet coûte 24 $. Coût au km = total ÷ distance.",
      p2: "Le calculateur convertit km/L, L/100km et mpg, et gère aller-retour, répétitions mensuelles et partage par passager dans tous les pays.",
      bullets: ["Carburant = distance ÷ consommation · Coût = litres × prix", "Au km = coût total ÷ distance", "Aller-retour ×2 · par personne ÷ passagers"],
      q1: "Combien de carburant pour 100 km ?",
      a1: "100 ÷ votre km/L : à 15 km/L il faut ~6,7 litres. À 7 L/100km, exactement 7 litres.",
      q2: "Quelle formule pour le coût au mile ?",
      a2: "(Prix par gallon ÷ MPG) = coût par mile. Multipliez par les miles du trajet.",
    },
    "8th-pay-commission": {
      h2: "What is the 8th Pay Commission fitment factor?",
      p1: "The multiplier converting 7th CPC basic pay to 8th CPC basic: New Basic = Current Basic × Fitment Factor. Consensus ~1.92x (7th CPC used 2.57x); unions demand up to 3.83x. DA resets to 0% with HRA at 30/20/10%.",
      p2: "Effective 1 January 2026 with arrears after the report (expected mid-2027). Projections, not official figures.",
      bullets: ["1.92x → ₹18,000 becomes ₹34,560", "DA 0% · HRA X30 / Y20 / Z10", "Arrears from 1 Jan 2026"],
      q1: "How is new basic pay calculated?",
      a1: "Current 7th CPC basic × fitment factor, then reset DA and slab HRA on the new basic.",
      q2: "When will it be implemented?",
      a2: "Fixation from 1 Jan 2026; cash payout after the report and approval.",
    },
  },
  de: {
    adsense: {
      h2: "Wie viel zahlt AdSense pro 1.000 Aufrufe?",
      p1: "2026 zahlt AdSense ca. $2,50 bis $45+ pro 1.000 Seitenaufrufe. Finanzen, Versicherungen, SaaS und Recht mit Tier-1-Traffic (US, UK, CA, AU) erreichen $25–$60 Seiten-RPM; Entertainment und Gaming liegen bei $2–$7. Formel: Umsatz = (Aufrufe × RPM) / 1.000. Google teilt 68 % mit Publishern.",
      p2: "Entscheidend: Geografie (Tier 1 zahlt 4–10x mehr als Tier 3), Sichtbarkeit über 70 % (bis 3x Gebote) und AdBlock-Verlust (15–45 %). Q4-Weihnachtsbudgets heben CPMs um 30–55 % über Januar.",
      bullets: ["$1.000/Monat ≈ 40.000 Aufrufe bei $25 RPM · ≈166.000 bei $6", "Anteil: 68 % Content / 51 % Suche", "Ziele: Sichtbarkeit >70 % · 2–4 Blöcke pro Seite"],
      q1: "Was ist der Unterschied zwischen Seiten-RPM und CPC?",
      a1: "Seiten-RPM misst den Ertrag pro 1.000 Seitenaufrufe über alle Blöcke. CPC ist der Klickpreis eines Werbenden.",
      q2: "Wie viel Traffic braucht man für $1.000 im Monat?",
      a2: "Ca. 40.000 Aufrufe bei $25 RPM (Finanzen) oder ca. 166.000 bei $6 RPM (allgemein).",
    },
    youtube: {
      h2: "Wie viel zahlt YouTube pro 1.000 Aufrufe?",
      p1: "2026 liegt der Long-Form-RPM bei $1,50 bis $35+ pro 1.000 Aufrufe. Finanzen, Krypto und SaaS erreichen $15–$35 in Tier 1; Gaming und Entertainment liegen bei $2–$6. YouTube behält 45 %, Creator erhalten 55 %. Shorts werden separat gepoolt bei ca. $0,03–$0,09 RPM.",
      p2: "Videos über 8 Minuten schalten Mid-Rolls frei (+35–60 % RPM). Mitgliedschaften ($4,99/Monat, 70 % netto) und Super Chats kommen dazu. YPP-Zugang: 1.000 Abos + 4.000 Stunden oder 500 Abos + 3M Shorts in 90 Tagen.",
      bullets: ["RPM = CPM × 55 % × monetarisierte Aufrufe", "1M Aufrufe Finanzen ≈ $15.000–$35.000 · Gaming ≈ $2.000–$6.000", "1M Shorts ≈ $30–$90"],
      q1: "Warum ist RPM niedriger als CPM?",
      a1: "CPM ist der Werbekundenpreis; RPM Ihr Netto nach 45 % Anteil und nicht-monetarisierten Aufrufen.",
      q2: "Wie viele Aufrufe braucht man für $1.000 im Monat?",
      a2: "Ca. 200.000 bei $5 RPM oder ca. 50.000 bei $20 RPM (Finanzen, US-Publikum).",
    },
    tiktok: {
      h2: "Wie viel zahlt TikTok pro 1.000 Aufrufe?",
      p1: "Das Creator-Rewards-Programm zahlt ca. $0,40–$1,20 pro 1.000 qualifizierte Aufrufe. Nur Originale über 1 Minute mit 5+ Sekunden Watchtime im Für-Dich-Feed zählen (~45 % aller Aufrufe). 1M Aufrufe ≈ $200–$800 effektiv.",
      p2: "LIVE-Geschenke werden zu Diamonds à $0,005 (50 % netto): 100.000 Diamonds = $250. Tragen Sie Views, Quali-Rate und Diamonds oben ein.",
      bullets: ["Qualifiziert = >1 Min · >5 s · Für-Dich-Feed", "1 Diamond = $0,005 (50 % netto) · 200 = $1", "TikTok Shop bringt +10–20 % Provision"],
      q1: "Wie viel sind 1.000 TikTok-Diamonds wert?",
      a1: "1.000 Diamonds = $5 netto für Creator. Zuschauer zahlten ca. das Doppelte in Coins.",
      q2: "Zählen alle TikTok-Aufrufe für die Vergütung?",
      a2: "Nein. Unter 5 Sekunden, außerhalb des Für-Dich-Feeds und unter 1 Minute sind ausgeschlossen.",
    },
    twitch: {
      h2: "Wie viel verdient man pro Twitch-Sub?",
      p1: "Ein Tier-1-Sub ($4,99) bringt $2,49 bei 50/50 und ~$3,49 bei 70/30 Partner Plus. 100 Tier-1-Subs ≈ $249/Monat bei 50/50 gegenüber ≈$349 bei 70/30.",
      p2: "Partner Plus gibt 60/40 ab 100 Plus Points und 70/30 ab 350 Punkten über 3 Monate (Tier 1 = 1 Pt, Tier 2 = 2, Tier 3 = 6). Das AIP-Programm zahlt ~$3,50–$10 pro Zuschauerstunde bei 2–3 Werbeminuten pro Stunde, plus $0,01 pro Bit.",
      bullets: ["100 Tier-1-Subs: $249 (50/50) · $349 (70/30)", "Plus Points: 100 → 60/40 · 350 → 70/30", "Bits: 100 Bits = $1 · 1.000 Bits = $10"],
      q1: "Wie bekommt man den 70/30-Split auf Twitch?",
      a1: "350 Plus Points 3 Monate in Folge aus wiederkehrenden Paid-Subs halten (ohne Prime/Einzel-Gifts).",
      q2: "Was zahlt das Twitch-Werbeprogramm AIP?",
      a2: "Einen festen Stundensatz für 2–3 Minuten Werbung pro Stunde; oben mit CCV berechnen.",
    },
    kick: {
      h2: "Wie viel zahlt Kick pro Sub?",
      p1: "Kick behält 5 % und zahlt 95 %: $4,74 netto pro $4,99-Abo — fast doppelt so viel wie $2,49 bei Twitch. 100 Subs ≈ $474/Monat, 1.000 Subs ≈ $4.740/Monat allein aus Subs.",
      p2: "Das KCP-Programm zahlt ca. $16–$40+/Std. nach durchschnittlichen Zuschauern (CCV), Stunden und Chat. Direkte Trinkgelder sind 100 % netto.",
      bullets: ["$4,74 netto pro Sub (95/5) vs. $2,49 Twitch", "KCP ≈ $16–$40+/Std. nach CCV", "100 Subs ≈ $474/Monat · 1.000 ≈ $4.740/Monat"],
      q1: "Zahlt Kick wirklich $16 pro Stunde?",
      a1: "Geeignete Partner erhalten einen CCV-gestaffelten Stundensatz; oben KCP aktivieren.",
      q2: "Zahlt Kick besser als Twitch?",
      a2: "Pro Sub ja: 95/5 gegen 50/50–70/30. Oben bei gleichem CCV vergleichen.",
    },
    runway: {
      h2: "Wie lange reicht mein Geld?",
      p1: "Saldo ÷ monatliche Lücke: $60.000 ÷ $5.000/Monat = 12 Monate. Mit Rendite hält es länger — bei 8 % p.a. trägt ein Saldo ca. 0,67 % Monatsentnahme fast dauerhaft. Oben Beträge eingeben für die Jahresprojektion.",
      p2: "Das ist Entnahmeplan-Mathematik (SWP): fixer Monatsbetrag raus, Rest bleibt investiert. Die 4-%-Regel ist dieselbe Idee mit 4 %/Jahr.",
      bullets: ["Reichweite ≈ Saldo ÷ (Ausgaben − Einnahmen)", "8 % trägt ≈0,67 %/Monat langfristig", "+1 % Inflation = deutlich weniger Jahre: oben testen"],
      q1: "Wie viel kann ich monatlich entnehmen?",
      a1: "0,5–0,67 % des Saldos bei 6–8 % Rendite testen und Breakeven prüfen.",
      q2: "Ist das ein Entnahmeplan-Rechner?",
      a2: "Ja: fixe Monatsentnahme bei thesaurierendem Rest, minus Inflationssteigerung.",
    },
    "fuel-cost-calculator": {
      h2: "Wie berechnet man die Spritkosten einer Fahrt?",
      p1: "Kraftstoff = Strecke ÷ Verbrauch; Kosten = Liter × Preis. Beispiel: 300 km bei 15 km/L = 20 Liter; bei $1,20/L kostet die Fahrt $24. Kosten pro km = Gesamt ÷ Strecke.",
      p2: "Der Rechner wandelt km/L, L/100km und mpg um und berücksichtigt Hin+Rück, Monatswiederholung und Aufteilung pro Mitfahrer weltweit.",
      bullets: ["Liter = Strecke ÷ Verbrauch · Kosten = Liter × Preis", "Pro km = Gesamtkosten ÷ Strecke", "Hin+Rück ×2 · pro Person ÷ Mitfahrer"],
      q1: "Wie viel Sprit braucht man für 100 km?",
      a1: "100 ÷ Ihr km/L: bei 15 km/L ca. 6,7 Liter. Bei 7 L/100km exakt 7 Liter.",
      q2: "Was kostet eine Meile?",
      a2: "(Gallonpreis ÷ MPG) = Kosten pro Meile. Mal Meilen für die Gesamtkosten.",
    },
    "8th-pay-commission": {
      h2: "What is the 8th Pay Commission fitment factor?",
      p1: "The multiplier converting 7th CPC basic pay to 8th CPC basic: New Basic = Current Basic × Fitment Factor. Consensus ~1.92x (7th CPC used 2.57x); unions demand up to 3.83x. DA resets to 0% with HRA at 30/20/10%.",
      p2: "Effective 1 January 2026 with arrears after the report (expected mid-2027). Projections, not official figures.",
      bullets: ["1.92x → ₹18,000 becomes ₹34,560", "DA 0% · HRA X30 / Y20 / Z10", "Arrears from 1 Jan 2026"],
      q1: "How is new basic pay calculated?",
      a1: "Current 7th CPC basic × fitment factor, then reset DA and slab HRA on the new basic.",
      q2: "When will it be implemented?",
      a2: "Fixation from 1 Jan 2026; cash payout after the report and approval.",
    },
  },
  pt: {
    adsense: {
      h2: "Quanto o AdSense paga por 1.000 visitas?",
      p1: "Em 2026 o AdSense paga cerca de $2,50 a mais de $45 por 1.000 páginas vistas. Finanças, seguros, SaaS e jurídico com tráfego Tier 1 (EUA, Reino Unido, Canadá) alcançam $25–$60 de RPM; entretenimento e games ficam em $2–$7. Fórmula: Receita = (Visitas × RPM) / 1.000. O Google repassa 68% ao publicador.",
      p2: "O que mais muda o RPM: geografia (Tier 1 paga 4–10x o Tier 3), visibilidade ativa acima de 70% (até 3x em lances) e perda por AdBlock (15–45%). O Q4 de festas sobe os CPMs 30–55% sobre janeiro.",
      bullets: ["$1.000/mês ≈ 40.000 visitas com RPM $25 · ≈166.000 com RPM $6", "Repartição: 68% conteúdo / 51% busca", "Metas: visibilidade >70% · 2–4 blocos por página"],
      q1: "Qual a diferença entre RPM da página e CPC?",
      a1: "O RPM mede ganhos por 1.000 páginas vistas com todos os blocos. O CPC é o que um anunciante paga por clique.",
      q2: "Quantas visitas preciso para faturar $1.000 por mês?",
      a2: "Cerca de 40.000 com RPM $25 (finanças) ou 166.000 com RPM $6 (nicho geral).",
    },
    youtube: {
      h2: "Quanto o YouTube paga por 1.000 visualizações?",
      p1: "Em 2026 o RPM de vídeos longos vai de $1,50 a mais de $35 por 1.000 views. Finanças, cripto e SaaS alcançam $15–$35 no Tier 1; games e entretenimento ficam em $2–$6. O YouTube fica com 45% e paga 55%. Shorts são rateados à parte, cerca de $0,03–$0,09 de RPM.",
      p2: "Vídeos acima de 8 minutos liberam mid-rolls (+35–60% de RPM). Membros ($4,99/mês, 70% líquido) e Super Chats somam. Para monetizar: 1.000 inscritos + 4.000 horas, ou 500 inscritos + 3M de Shorts em 90 dias.",
      bullets: ["RPM = CPM × 55% × views monetizadas", "1M views finanças ≈ $15.000–$35.000 · games ≈ $2.000–$6.000", "1M Shorts ≈ $30–$90"],
      q1: "Por que o RPM é menor que o CPM?",
      a1: "O CPM é o custo do anunciante; o RPM é o seu líquido após os 45% e as views sem anúncio.",
      q2: "Quantas views preciso para $1.000 por mês?",
      a2: "Cerca de 200.000 com RPM $5, ou 50.000 com RPM $20 (finanças, público EUA).",
    },
    tiktok: {
      h2: "Quanto o TikTok paga por 1.000 visualizações?",
      p1: "O Creator Rewards paga cerca de $0,40–$1,20 por 1.000 views qualificadas. Só valem vídeos originais acima de 1 min assistidos 5s+ no «Para você» (~45% do total). 1M de views totais ≈ $200–$800 efetivos.",
      p2: "Presentes LIVE viram diamantes a $0,005 cada (50% líquido): 100.000 diamantes = $250. Informe views, taxa qualificada e diamantes acima.",
      bullets: ["Qualificada = >1 min · >5s · feed «Para você»", "1 diamante = $0,005 (50% líquido) · 200 = $1", "TikTok Shop soma 10–20% de comissão"],
      q1: "Quanto valem 1.000 diamantes do TikTok?",
      a1: "1.000 diamantes = $5 líquidos ao criador. O espectador pagou cerca do dobro em moedas.",
      q2: "Todas as views do TikTok contam para o pagamento?",
      a2: "Não. Abaixo de 5 segundos, fora do «Para você» e vídeos abaixo de 1 min ficam de fora.",
    },
    twitch: {
      h2: "Quanto a Twitch paga por sub?",
      p1: "Um sub Tier 1 ($4,99) paga $2,49 no 50/50 e ~$3,49 no 70/30 do Partner Plus. 100 subs Tier 1 ≈ $249/mês no 50/50 contra ≈$349/mês no 70/30.",
      p2: "O Partner Plus dá 60/40 com 100 Plus Points e 70/30 com 350 pontos por 3 meses (Tier 1 = 1 pt, Tier 2 = 2, Tier 3 = 6). O programa AIP soma ~$3,50–$10 por hora-espectador com 2–3 min de ads por hora, mais $0,01 por Bit.",
      bullets: ["100 subs Tier 1: $249 (50/50) · $349 (70/30)", "Plus Points: 100 → 60/40 · 350 → 70/30", "Bits: 100 bits = $1 · 1.000 bits = $10"],
      q1: "Como consigo o 70/30 na Twitch?",
      a1: "Mantenha 350 Plus Points por 3 meses seguidos com subs pagas recorrentes (sem Prime nem gifts avulsos).",
      q2: "Quanto paga o programa AIP de anúncios?",
      a2: "Uma taxa horária fixa por exibir 2–3 min de ads por hora; calcule acima com seu CCV.",
    },
    kick: {
      h2: "Quanto a Kick paga por sub?",
      p1: "A Kick fica com 5% e paga 95%: $4,74 líquidos por assinatura de $4,99, quase o dobro dos $2,49 da Twitch. 100 subs ≈ $474/mês e 1.000 subs ≈ $4.740/mês só em subs.",
      p2: "O programa KCP soma cerca de $16–$40+/hora conforme espectadores simultâneos (CCV), horas e chat. Gorjetas diretas são 100% líquidas.",
      bullets: ["$4,74 líquidos por sub (95/5) contra $2,49 na Twitch", "KCP ≈ $16–$40+/hora por CCV", "100 subs ≈ $474/mês · 1.000 ≈ $4.740/mês"],
      q1: "A Kick paga mesmo $16 por hora?",
      a1: "Parceiros elegíveis recebem fixo horário por CCV e horas; ative o KCP acima.",
      q2: "A Kick paga melhor que a Twitch?",
      a2: "Por sub, sim: 95/5 contra 50/50–70/30. Compare com o mesmo CCV acima.",
    },
    runway: {
      h2: "Quanto tempo minhas economias duram?",
      p1: "Divida o saldo pelo déficit mensal: $60.000 ÷ $5.000/mês = 12 meses. Com rendimento dura mais — a 8% ao ano, o saldo suporta ~0,67% de retirada mensal quase para sempre. Informe os valores acima para a projeção ano a ano.",
      p2: "É a matemática do saque sistemático (SWP): valor fixo sai todo mês enquanto o resto rende. A regra dos 4% é a mesma ideia a 4%/ano.",
      bullets: ["Duração ≈ saldo ÷ (gastos − renda)", "8% sustenta ≈0,67%/mês no longo prazo", "+1% de inflação = anos a menos: teste acima"],
      q1: "Quanto posso sacar por mês com segurança?",
      a1: "Teste 0,5–0,67% do saldo ao mês com 6–8% de retorno e confira o ponto de equilíbrio.",
      q2: "Isto é uma calculadora SWP?",
      a2: "Sim: saque mensal fixo com o restante capitalizando, menos a alta da inflação.",
    },
    "fuel-cost-calculator": {
      h2: "Como calcular o custo de combustível da viagem?",
      p1: "Combustível = Distância ÷ Consumo; Custo = Litros × Preço. Exemplo: 300 km a 15 km/L = 20 litros; a $1,20/L a viagem custa $24. Custo por km = total ÷ distância.",
      p2: "A calculadora converte km/L, L/100km e mpg e inclui ida e volta, repetições mensais e divisão por passageiro em qualquer país.",
      bullets: ["Litros = distância ÷ consumo · Custo = litros × preço", "Por km = custo total ÷ distância", "Ida e volta ×2 · por pessoa ÷ passageiros"],
      q1: "Quanto combustível gasto em 100 km?",
      a1: "100 ÷ seu km/L: com 15 km/L precisa de ~6,7 litros. Com 7 L/100km, exatamente 7 litros.",
      q2: "Qual a fórmula do custo por milha?",
      a2: "(Preço por galão ÷ MPG) = custo por milha. Multiplique pelas milhas da viagem.",
    },
    "8th-pay-commission": {
      h2: "What is the 8th Pay Commission fitment factor?",
      p1: "The multiplier converting 7th CPC basic pay to 8th CPC basic: New Basic = Current Basic × Fitment Factor. Consensus ~1.92x (7th CPC used 2.57x); unions demand up to 3.83x. DA resets to 0% with HRA at 30/20/10%.",
      p2: "Effective 1 January 2026 with arrears after the report (expected mid-2027). Projections, not official figures.",
      bullets: ["1.92x → ₹18,000 becomes ₹34,560", "DA 0% · HRA X30 / Y20 / Z10", "Arrears from 1 Jan 2026"],
      q1: "How is new basic pay calculated?",
      a1: "Current 7th CPC basic × fitment factor, then reset DA and slab HRA on the new basic.",
      q2: "When will it be implemented?",
      a2: "Fixation from 1 Jan 2026; cash payout after the report and approval.",
    },
  },
  ko: {
    adsense: {
      h2: "애드센스는 조회수 1,000회당 얼마를 지급하나요?",
      p1: "2026년 애드센스는 페이지뷰 1,000회당 약 $2.50~$45 이상을 지급합니다. Tier 1 트래픽(미국·영국·캐나다)의 금융·보험·SaaS·법률은 페이지 RPM $25~$60, 엔터·게임은 $2~$7 수준입니다. 공식: 수익＝(페이지뷰×페이지 RPM)÷1,000. 구글은 68%를 지급합니다.",
      p2: "핵심 변수는 지역(Tier 1이 Tier 3의 4~10배), 활성 가시성 70% 이상(최대 3배 입찰), 애드블록 손실(15~45%)입니다. Q4 성수기는 1월 대비 CPM이 30~55% 상승합니다.",
      bullets: ["월 $1,000＝RPM $25면 약 4만뷰·$6이면 약 16.6만뷰", "수익 배분: 콘텐츠 68% / 검색 51%", "목표: 가시성 70%↑·광고 2~4개"],
      q1: "페이지 RPM과 CPC의 차이는?",
      a1: "페이지 RPM은 전체 광고 포함 1,000뷰당 수익, CPC는 클릭 1회당 광고주 지불액입니다.",
      q2: "월 $1,000 버는 데 필요한 조회수는?",
      a2: "RPM $25면 약 4만뷰, $6이면 약 16.6만뷰가 필요합니다.",
    },
    youtube: {
      h2: "유튜브는 조회수 1,000회당 얼마를 지급하나요?",
      p1: "2026년 롱폼 RPM은 1,000회당 $1.50~$35 이상입니다. 금융·암호화폐·SaaS는 Tier 1에서 $15~$35, 게임·엔터는 $2~$6 수준. 유튜브가 45%를 가져가고 창작자는 55%를 받습니다. 쇼츠는 별도 풀로 약 $0.03~$0.09 RPM입니다.",
      p2: "8분 이상 영상은 중간광고로 RPM이 약 35~60% 상승합니다. 멤버십($4.99/월·70% 정산)과 슈퍼챗이 추가됩니다. 수익창출 조건: 구독자 1,000명＋4,000시간 또는 500명＋90일 쇼츠 300만회입니다.",
      bullets: ["RPM＝CPM×55%×수익화 시청률", "100만회: 금융 $15,000~$35,000·게임 $2,000~$6,000", "쇼츠 100만회≈$30~$90"],
      q1: "RPM이 CPM보다 낮은 이유는?",
      a1: "CPM은 광고주 지불액, RPM은 45% 수수료 제외·비수익 조회 포함 수령액이기 때문입니다.",
      q2: "월 $1,000 버는 데 필요한 조회수는?",
      a2: "RPM $5면 월 약 20만회, $20(금융·미국향)이면 약 5만회가 필요합니다.",
    },
    tiktok: {
      h2: "틱톡은 조회수 1,000회당 얼마를 지급하나요?",
      p1: "크리에이터 리워드는 적격 조회수 1,000회당 약 $0.40~$1.20을 지급합니다. 1분 이상 오리지널을 추천 피드에서 5초 이상 시청한 경우만 적격(약 45%)이며, 100만회 총조회수의 실효 수익은 약 $200~$800입니다.",
      p2: "LIVE 선물은 다이아몬드 1개당 $0.005, 정산율 50%: 10만 다이아＝$250. 위에서 월 조회수·적격률·다이아를 입력하세요.",
      bullets: ["적격＝1분↑·5초↑·추천피드", "1다이아＝$0.005(50%)·200개＝$1", "틱톡샵 수수료 10~20% 추가"],
      q1: "다이아몬드 1,000개의 가치는?",
      a1: "창작자 수령액 $5. 시청자는 코인으로 약 2배를 결제했습니다.",
      q2: "모든 조회수가 정산되나요?",
      a2: "아닙니다. 5초 미만·추천 외·1분 미만 영상은 제외됩니다.",
    },
    twitch: {
      h2: "트위치 구독 1개당 수익은 얼마인가요?",
      p1: "$4.99 Tier 1 구독은 50/50에서 $2.49, 파트너 플러스 70/30에서 약 $3.49입니다. 100개 기준 월 $249(50/50) 대 $349(70/30)입니다.",
      p2: "파트너 플러스는 100포인트에 60/40, 350포인트 3개월 유지 시 70/30(Tier 1＝1pt·Tier 2＝2pt·Tier 3＝6pt)입니다. AIP 광고는 시간당 2~3분 편성 시 시청자 1인시당 약 $3.50~$10, 비트는 1bit＝$0.01입니다.",
      bullets: ["Tier 1×100개: $249(50/50)·$349(70/30)", "100pt→60/40·350pt→70/30", "100비트＝$1·1,000비트＝$10"],
      q1: "70/30 등급 조건은?",
      a1: "유료 정기구독으로 350포인트를 3개월 연속 유지(프라임·일회성 선물 제외)하세요.",
      q2: "AIP 광고 수익은 얼마인가요?",
      a2: "시간당 2~3분 편성 시 고정 시급. 위에서 CCV·방송시간으로 계산하세요.",
    },
    kick: {
      h2: "킥 구독 1개당 수익은 얼마인가요?",
      p1: "킥은 수수료 5%·배분 95%로 $4.99 구독당 순수익 $4.74이며 트위치 $2.49의 약 2배입니다. 100개면 월 약 $474, 1,000개면 약 $4,740(구독만)입니다.",
      p2: "KCP 프로그램은 평균 동시시청자(CCV)·방송시간·채팅 활성도에 따라 약 $16~$40+/시를 지급합니다. 직접 후원은 100% 정산입니다.",
      bullets: ["$4.74/개(95/5) 대 트위치 $2.49", "KCP 시급≈$16~$40+/시", "100개≈$474/월·1,000개≈$4,740/월"],
      q1: "정말 시급 $16을 받나요?",
      a1: "조건 달성 파트너에게 CCV 연동 시급이 지급됩니다. 위에서 KCP를 켜세요.",
      q2: "킥이 트위치보다 잘 버나요?",
      a2: "구독 단가는 약 2배(95/5 대 50/50~70/30). 같은 CCV로 위에서 비교하세요.",
    },
    runway: {
      h2: "내 저축은 몇 년 버틸까요?",
      p1: "잔액÷월 부족액이 기준: $60,000÷$5,000/월＝12개월. 수익률이 있으면 연장되며 연 8%なら 월 0.67% 인출을 거의 유지할 수 있습니다. 위에서 원금·인출·수익률·인플레를 입력하세요.",
      p2: "매월 정액 인출＋잔액 운용의 SWP 계산이며 4%룰(연 4% 인출)과 같은 생각입니다.",
      bullets: ["버팀기간≈잔액÷(지출−수입)", "연 8%면 월 0.67%가 기준", "인플레＋1%에 기간 급감: 위에서 테스트"],
      q1: "월 얼마까지 인출할 수 있나요?",
      a1: "수익률 6~8% 기준 월 0.5~0.67%를 시험하고 손익분기점을 확인하세요.",
      q2: "SWP 계산기인가요?",
      a2: "네. 정액 월 인출＋잔액 복리−인플레 반영 계산입니다.",
    },
    "fuel-cost-calculator": {
      h2: "여행 연료비는 어떻게 계산하나요?",
      p1: "필요 연료＝거리÷연비, 비용＝연료×단가. 예: 300km를 15km/L로 주행하면 20L, $1.20/Lなら $24. km당＝합계÷거리입니다.",
      p2: "위 계산기는 km/L·L/100km·mpg를 자동 변환하고 왕복·월 반복·동승자 분담을 전 세계 지원합니다.",
      bullets: ["연료＝거리÷연비·비용＝연료×단가", "km당＝합계÷거리", "왕복×2·1인당÷동승자"],
      q1: "100km 주행 연료는?",
      a1: "100÷km/L: 15km/Lなら 약 6.7L. 7L/100kmなら 정확히 7L입니다.",
      q2: "마일당 비용 공식은?",
      a2: "(갤런당 가격÷MPG)＝마일당 비용. 거리를 곱해 합계를 구합니다.",
    },
    "8th-pay-commission": {
      h2: "What is the 8th Pay Commission fitment factor?",
      p1: "The multiplier converting 7th CPC basic pay to 8th CPC basic: New Basic = Current Basic × Fitment Factor. Consensus ~1.92x (7th CPC used 2.57x); unions demand up to 3.83x. DA resets to 0% with HRA at 30/20/10%.",
      p2: "Effective 1 January 2026 with arrears after the report (expected mid-2027). Projections, not official figures.",
      bullets: ["1.92x → ₹18,000 becomes ₹34,560", "DA 0% · HRA X30 / Y20 / Z10", "Arrears from 1 Jan 2026"],
      q1: "How is new basic pay calculated?",
      a1: "Current 7th CPC basic × fitment factor, then reset DA and slab HRA on the new basic.",
      q2: "When will it be implemented?",
      a2: "Fixation from 1 Jan 2026; cash payout after the report and approval.",
    },
  },
  it: {
    adsense: {
      h2: "Quanto paga AdSense ogni 1.000 visite?",
      p1: "Nel 2026 AdSense paga circa $2,50–$45+ ogni 1.000 pagine viste. Finanza, assicurazioni, SaaS e legale con traffico Tier 1 (USA, UK, CA, AU) raggiungono $25–$60 di RPM pagina; intrattenimento e gaming in media $2–$7. Formula: Ricavi = (Visite × RPM) / 1.000. Google riconosce il 68% agli editori.",
      p2: "Contano di più: geografia (Tier 1 paga 4–10x il Tier 3), viewability attiva oltre il 70% (fino a 3x di offerte) e perdita da AdBlock (15–45%). Il Q4 natalizio alza i CPM del 30–55% su gennaio.",
      bullets: ["$1.000/mese ≈ 40.000 visite a RPM $25 · ≈166.000 a RPM $6", "Split: 68% contenuti / 51% ricerca", "Obiettivi: viewability >70% · 2–4 blocchi per pagina"],
      q1: "Che differenza c'è tra RPM pagina e CPC?",
      a1: "Il RPM misura i ricavi ogni 1.000 pagine viste con tutti i blocchi. Il CPC è quanto paga un inserzionista per clic.",
      q2: "Quante visite servono per $1.000 al mese?",
      a2: "Circa 40.000 con RPM $25 (finanza) o 166.000 con RPM $6 (nicchia generica).",
    },
    youtube: {
      h2: "Quanto paga YouTube ogni 1.000 visualizzazioni?",
      p1: "Nel 2026 il RPM long-form va da $1,50 a oltre $35 ogni 1.000 views. Finanza, crypto e SaaS arrivano a $15–$35 in Tier 1; gaming e intrattenimento in media $2–$6. YouTube trattiene il 45% e paga il 55%. Gli Shorts sono a parte, circa $0,03–$0,09 di RPM.",
      p2: "I video oltre 8 minuti sbloccano i mid-roll (+35–60% di RPM). Membri ($4,99/mese, 70% netto) e Super Chat si sommano. Per monetizzare: 1.000 iscritti + 4.000 ore, oppure 500 iscritti + 3M di Shorts in 90 giorni.",
      bullets: ["RPM = CPM × 55% × views monetizzate", "1M views finanza ≈ $15.000–$35.000 · gaming ≈ $2.000–$6.000", "1M Shorts ≈ $30–$90"],
      q1: "Perché il RPM è più basso del CPM?",
      a1: "Il CPM è il costo inserzionista; il RPM è il tuo netto dopo il 45% e le views non monetizzate.",
      q2: "Quante views servono per $1.000 al mese?",
      a2: "Circa 200.000 con RPM $5, o 50.000 con RPM $20 (finanza, pubblico USA).",
    },
    tiktok: {
      h2: "Quanto paga TikTok ogni 1.000 visualizzazioni?",
      p1: "Il Creator Rewards paga circa $0,40–$1,20 ogni 1.000 views qualificate. Contano solo video originali oltre 1 minuto visti 5s+ da «Per te» (~45% del totale). 1M di views totali ≈ $200–$800 effettivi.",
      p2: "I regali LIVE diventano diamanti a $0,005 l'uno (50% netto): 100.000 diamanti = $250. Inserisci views, tasso qualificato e diamanti sopra.",
      bullets: ["Qualificata = >1 min · >5s · feed «Per te»", "1 diamante = $0,005 (50% netto) · 200 = $1", "TikTok Shop aggiunge 10–20% di commissioni"],
      q1: "Quanto valgono 1.000 diamanti TikTok?",
      a1: "1.000 diamanti = $5 netti al creator. Lo spettatore ha pagato circa il doppio in monete.",
      q2: "Tutte le views di TikTok contano per il pagamento?",
      a2: "No. Sotto 5 secondi, fuori «Per te» e video sotto 1 minuto sono esclusi.",
    },
    twitch: {
      h2: "Quanto paga Twitch per sub?",
      p1: "Una sub Tier 1 ($4,99) paga $2,49 al 50/50 e ~$3,49 al 70/30 Partner Plus. 100 sub Tier 1 ≈ $249/mese al 50/50 contro ≈$349/mese al 70/30.",
      p2: "Il Partner Plus dà 60/40 con 100 Plus Points e 70/30 con 350 punti per 3 mesi (Tier 1 = 1 pt, Tier 2 = 2, Tier 3 = 6). Il programma AIP aggiunge ~$3,50–$10 per ora-spettatore con 2–3 minuti di ads all'ora, più $0,01 per Bit.",
      bullets: ["100 sub Tier 1: $249 (50/50) · $349 (70/30)", "Plus Points: 100 → 60/40 · 350 → 70/30", "Bit: 100 bit = $1 · 1.000 bit = $10"],
      q1: "Come sblocco il 70/30 su Twitch?",
      a1: "Mantieni 350 Plus Points per 3 mesi consecutivi con sub pagate ricorrenti (senza Prime né gift una tantum).",
      q2: "Quanto paga il programma AIP?",
      a2: "Una tariffa oraria fissa per 2–3 minuti di spot all'ora; calcolala sopra con il tuo CCV.",
    },
    kick: {
      h2: "Quanto paga Kick per sub?",
      p1: "Kick trattiene il 5% e paga il 95%: $4,74 netti per abbonamento da $4,99, quasi il doppio dei $2,49 di Twitch. 100 sub ≈ $474/mese e 1.000 sub ≈ $4.740/mese di soli sub.",
      p2: "Il programma KCP aggiunge circa $16–$40+/ora in base a spettatori simultanei (CCV), ore e chat. Le mance dirette sono al 100% nette.",
      bullets: ["$4,74 netti per sub (95/5) contro $2,49 Twitch", "KCP ≈ $16–$40+/ora per CCV", "100 sub ≈ $474/mese · 1.000 ≈ $4.740/mese"],
      q1: "Kick paga davvero $16 all'ora?",
      a1: "I partner idonei ricevono un fisso orario per CCV e ore; attiva KCP sopra.",
      q2: "Kick paga meglio di Twitch?",
      a2: "Per sub sì: 95/5 contro 50/50–70/30. Confrontali a pari CCV sopra.",
    },
    runway: {
      h2: "Quanto dureranno i miei risparmi?",
      p1: "Dividi il saldo per il deficit mensile: $60.000 ÷ $5.000/mese = 12 mesi. Con rendimento dura di più — all'8% annuo, il saldo sostiene ~0,67% di prelievo mensile quasi per sempre. Inserisci i valori sopra per la proiezione anno per anno.",
      p2: "È la matematica del prelievo sistematico (SWP): un importo fisso esce ogni mese mentre il resto rende. La regola del 4% è la stessa idea al 4%/anno.",
      bullets: ["Durata ≈ saldo ÷ (spese − entrate)", "8% sostiene ≈0,67%/mese nel lungo periodo", "+1% di inflazione = anni in meno: provalo sopra"],
      q1: "Quanto posso prelevare al mese?",
      a1: "Prova 0,5–0,67% del saldo al mese con 6–8% di rendimento e verifica il pareggio.",
      q2: "È un calcolatore SWP?",
      a2: "Sì: prelievo mensile fisso con resto capitalizzato, meno l'aumento dell'inflazione.",
    },
    "fuel-cost-calculator": {
      h2: "Come si calcola il costo carburante di un viaggio?",
      p1: "Carburante = Distanza ÷ Consumo; Costo = Litri × Prezzo. Esempio: 300 km a 15 km/L = 20 litri; a $1,20/L il viaggio costa $24. Costo per km = totale ÷ distanza.",
      p2: "Il calcolatore converte km/L, L/100km e mpg e gestisce andata e ritorno, ripetizioni mensili e divisione per passeggero in ogni paese.",
      bullets: ["Litri = distanza ÷ consumo · Costo = litri × prezzo", "Per km = costo totale ÷ distanza", "Andata e ritorno ×2 · a persona ÷ passeggeri"],
      q1: "Quanto carburante serve per 100 km?",
      a1: "100 ÷ il tuo km/L: con 15 km/L servono ~6,7 litri. Con 7 L/100km, esattamente 7 litri.",
      q2: "Qual è la formula del costo per miglio?",
      a2: "(Prezzo per gallone ÷ MPG) = costo per miglio. Moltiplica per le miglia del viaggio.",
    },
    "8th-pay-commission": {
      h2: "What is the 8th Pay Commission fitment factor?",
      p1: "The multiplier converting 7th CPC basic pay to 8th CPC basic: New Basic = Current Basic × Fitment Factor. Consensus ~1.92x (7th CPC used 2.57x); unions demand up to 3.83x. DA resets to 0% with HRA at 30/20/10%.",
      p2: "Effective 1 January 2026 with arrears after the report (expected mid-2027). Projections, not official figures.",
      bullets: ["1.92x → ₹18,000 becomes ₹34,560", "DA 0% · HRA X30 / Y20 / Z10", "Arrears from 1 Jan 2026"],
      q1: "How is new basic pay calculated?",
      a1: "Current 7th CPC basic × fitment factor, then reset DA and slab HRA on the new basic.",
      q2: "When will it be implemented?",
      a2: "Fixation from 1 Jan 2026; cash payout after the report and approval.",
    },
  },
};

export const PlatformSeoSpotlight: React.FC<{ platform: string }> = ({ platform }) => {
  const { language } = useTranslation();
  // AdMob stays exactly as-is (it already ranks). Home/trust/404 have own content.
  if (platform === "admob" || platform === "home" || platform === "about" || platform === "contact" || platform === "privacy" || platform === "terms" || platform === "disclaimer" || platform === "404") {
    return null;
  }
  const table = SPOTLIGHT[language] || SPOTLIGHT.en;
  const entry = table[platform] || SPOTLIGHT.en[platform];
  if (!entry) return null;
  return (
    <section aria-label={entry.h2} className="border border-dashed border-neutral-300 dark:border-neutral-800 rounded-2xl p-5 sm:p-6 bg-white dark:bg-neutral-900 space-y-3">
      <h2 className="text-base sm:text-lg font-black font-mono tracking-tight text-neutral-950 dark:text-white">{entry.h2}</h2>
      <p className="text-xs font-mono text-neutral-600 dark:text-neutral-400 leading-relaxed">{entry.p1}</p>
      <p className="text-xs font-mono text-neutral-600 dark:text-neutral-400 leading-relaxed">{entry.p2}</p>
      <ul className="flex flex-col gap-1.5">
        {entry.bullets.map((b) => (
          <li key={b} className="text-[11px] font-mono text-neutral-700 dark:text-neutral-300">→ {b}</li>
        ))}
      </ul>
      <div className="pt-2 border-t border-dashed border-neutral-200 dark:border-neutral-800 space-y-2.5">
        <div>
          <h3 className="text-xs font-mono font-bold text-neutral-900 dark:text-white">{entry.q1}</h3>
          <p className="text-[11px] font-mono text-neutral-600 dark:text-neutral-400 leading-relaxed mt-0.5">{entry.a1}</p>
        </div>
        <div>
          <h3 className="text-xs font-mono font-bold text-neutral-900 dark:text-white">{entry.q2}</h3>
          <p className="text-[11px] font-mono text-neutral-600 dark:text-neutral-400 leading-relaxed mt-0.5">{entry.a2}</p>
        </div>
      </div>
    </section>
  );
};
