import React from "react";

const pageWrapperClasses = "max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8 text-neutral-800 dark:text-neutral-300 font-mono text-sm leading-relaxed space-y-6";
const h1Classes = "text-2xl sm:text-3xl font-black text-neutral-950 dark:text-white mb-6 border-b border-dashed border-neutral-300 dark:border-neutral-800 pb-4";
const h2Classes = "text-xl font-bold text-neutral-900 dark:text-neutral-100 mt-8 mb-4";
const linkClasses = "text-blue-600 dark:text-blue-400 hover:underline";
const listClasses = "list-disc pl-6 space-y-2";

export const AboutPage = React.memo(() => (
  <div className={pageWrapperClasses}>
    <h1 className={h1Classes}>About AdMobRevenue</h1>
    <p>AdMobRevenue was created to help mobile app developers and web publishers accurately forecast their ad monetization income. We noticed that many calculators rely on outdated, static CPMs that do not reflect the reality of modern real-time bidding, seasonality, or geographic tier variations.</p>
    <p>Our tool aggregates verified industry benchmarks, format multipliers, and geographical data to provide deterministic revenue forecasting. Whether you're optimizing an existing app or planning a new website, our goal is to give you transparent, data-driven estimates.</p>
  </div>
));

export const ContactPage = React.memo(() => (
  <div className={pageWrapperClasses}>
    <h1 className={h1Classes}>Contact Us</h1>
    <p>If you have questions, business inquiries, or feedback regarding our forecasting models, please reach out to us.</p>
    <p><strong>Email:</strong> support@admobrevenue.pages.dev</p>
    <p>We aim to respond to all inquiries within 48 hours.</p>
  </div>
));

export const PrivacyPage = React.memo(() => (
  <div className={pageWrapperClasses}>
    <h1 className={h1Classes}>Privacy Policy</h1>
    <p className="text-neutral-500">Last updated: August 2026</p>
    <p>At AdMobRevenue, your privacy is our priority. This Privacy Policy explains how we collect, use, and protect your information.</p>
    <h2 className={h2Classes}>Information We Collect</h2>
    <p>We do not collect any personal data when you use the calculators. Your inputs (such as DAU, selected ad formats, etc.) are saved locally on your device using <code className="bg-neutral-100 dark:bg-neutral-800 px-1 py-0.5 rounded">localStorage</code> to provide a persistent experience. We use Google Analytics to understand general website traffic and usage patterns.</p>
    <h2 className={h2Classes}>Third-Party Services</h2>
    <p>We may use third-party vendors, including Google, who use cookies to serve ads based on your prior visits to our website or other websites. Google's use of advertising cookies enables it and its partners to serve ads to our users based on their visit to our sites and/or other sites on the Internet.</p>
    <p>You may opt out of personalized advertising by visiting <a href="https://www.google.com/settings/ads" target="_blank" rel="noopener noreferrer" className={linkClasses}>Ads Settings</a>.</p>
    <h2 className={h2Classes}>Contact Us</h2>
    <p>If you have any questions about this Privacy Policy, please contact us via our Contact page.</p>
  </div>
));

export const TermsPage = React.memo(() => (
  <div className={pageWrapperClasses}>
    <h1 className={h1Classes}>Terms of Service</h1>
    <p className="text-neutral-500">Last updated: August 2026</p>
    <p>By accessing or using AdMobRevenue, you agree to be bound by these Terms of Service.</p>
    <h2 className={h2Classes}>Use of the Tool</h2>
    <p>AdMobRevenue provides estimation tools for educational and planning purposes only. You agree not to use the site for any unlawful purpose or in any way that could damage, disable, or impair the service.</p>
    <h2 className={h2Classes}>Disclaimer of Warranties</h2>
    <p>The service is provided "as is" and "as available". We make no warranties, expressed or implied, regarding the accuracy, reliability, or availability of the revenue estimates provided.</p>
    <h2 className={h2Classes}>Limitation of Liability</h2>
    <p>In no event shall AdMobRevenue or its operators be liable for any indirect, incidental, special, or consequential damages arising out of your use of the service or reliance on the estimates provided.</p>
  </div>
));

export const DisclaimerPage = React.memo(() => (
  <div className={pageWrapperClasses}>
    <h1 className={h1Classes}>Disclaimer & Methodology</h1>
    <p><strong>Earnings Disclaimer:</strong> The outputs generated by AdMobRevenue are strict estimates and do not constitute guaranteed earnings. Actual revenue from Google AdMob or Google AdSense can and will vary significantly based on numerous factors.</p>
    <h2 className={h2Classes}>Methodology</h2>
    <p>Our calculators use a deterministic math engine based on industry averages for eCPM and RPM. We factor in:</p>
    <ul className={listClasses}>
      <li><strong>Geographic Tiers:</strong> Traffic from Tier 1 countries (e.g., US, UK) yields higher CPMs than Tier 3 countries.</li>
      <li><strong>Ad Formats:</strong> Rewarded Video and Interstitial ads typically offer higher payouts than standard Banners.</li>
      <li><strong>Seasonality:</strong> Ad spend historically increases in Q4 and dips in Q1.</li>
      <li><strong>Viewability & AdBlockers:</strong> Web revenue is adjusted for the percentage of users employing ad blockers and the strict viewability rate of your ad units.</li>
    </ul>
    <p>Please note that individual performance depends on app quality, user engagement, ad placement, Google's fill rate, and advertiser demand at any given time.</p>
  </div>
));
