import { CurrencyCode } from "../types";
import { formatCurrency } from "./currency";

export function exportCalculationCSV(
  type: "AdSense" | "AdMob",
  categoryName: string,
  trafficMetric: string,
  trafficValue: string,
  dailyRev: number,
  monthlyRev: number,
  annualRev: number,
  rateMetric: string,
  rateValue: string,
  formatBreakdown: { name: string; revenue: number; percentage: number }[],
  currency: CurrencyCode
) {
  const rows = [
    ["Metric", "Value"],
    ["Report Type", `${type} Revenue Estimate (2025-2026 Verified Engine)`],
    ["Industry / Category", categoryName],
    [trafficMetric, trafficValue],
    [rateMetric, rateValue],
    ["Currency", currency],
    ["Daily Net Revenue", formatCurrency(dailyRev, currency)],
    ["Monthly Net Revenue", formatCurrency(monthlyRev, currency)],
    ["Annual Projected Revenue", formatCurrency(annualRev, currency)],
    ["", ""],
    ["--- Ad Format Breakdown ---", ""],
    ...formatBreakdown.map((f) => [f.name, `${formatCurrency(f.revenue, currency)} (${f.percentage}%)`]),
    ["", ""],
    ["Generated By", "AdSense & AdMob Revenue Calculator (https://admob-adsense-calculator.pages.dev)"],
    ["Timestamp", new Date().toISOString()],
  ];

  const csvContent =
    "data:text/csv;charset=utf-8," +
    rows.map((e) => e.map((val) => `"${String(val).replace(/"/g, '""')}"`).join(",")).join("\n");

  const encodedUri = encodeURI(csvContent);
  const link = document.createElement("a");
  link.setAttribute("href", encodedUri);
  link.setAttribute(
    "download",
    `${type.toLowerCase()}-revenue-audit-${new Date().toISOString().slice(0, 10)}.csv`
  );
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function copyShareableLink(params: Record<string, any>): boolean {
  try {
    const encoded = btoa(JSON.stringify(params));
    const url = `${window.location.origin}${window.location.pathname}?calc=${encoded}`;
    navigator.clipboard.writeText(url);
    return true;
  } catch (err) {
    console.error("Failed to copy share link:", err);
    return false;
  }
}
